In [25]:
import torch

In [26]:
import torch
from torch.utils.data import DataLoader
from torch import nn
import torch.optim as optim
from datasetConLL2003 import SlidingWindowDataset
from modelConLL2003 import RNNBIOESTagger

print("Step 1: loading Train/Test/Validation datasets...")
print("*"*100)     
validation_dataset = DataLoader(dataset=SlidingWindowDataset("C:/Users/rahin/projects/paper-draft-03/data/raw/ConLL2003-bioes-valid.txt"),
                                batch_size=64,
                                shuffle=False)
print("*"*100)                                

print("All datasets successfully loaded!")

Step 1: loading Train/Test/Validation datasets...
****************************************************************************************************
loading dictionaries...
done
Performing dataset pre-processing activities...
loading dataset: ConLL2003-bioes-valid.txt
done
Parsing the dataset now...
converting tokens to indices to tensors
done
Length matches! Hurray!
****************************************************************************************************
All datasets successfully loaded!


In [27]:
for idx, (sample, label) in enumerate(validation_dataset):

    if idx > 5:
        break

    print(sample[0])
    print(label[0])

tensor([18122, 22892,  6603, 11657, 14828,  4595, 22902, 21347,  8802,  9933,
        26565, 30338, 30338, 30338, 30338, 30338, 30338, 30338, 30338, 30338,
        30338, 30338, 30338, 30338, 30338, 30338, 30338, 30338, 30338, 30338,
        30338, 30338, 30338, 30338, 30338, 30338, 30338, 30338, 30338, 30338,
        30338, 30338, 30338, 30338, 30338, 30338, 30338, 30338, 30338, 30338])
tensor([10, 26, 15, 26, 24,  8, 26, 24, 24, 24, 29, 34, 34, 34, 34, 34, 34, 34,
        34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
        34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34])
tensor([14501,  4466, 14760, 10226, 15579,  9637, 22776, 28907, 13927, 21022,
        19107, 26859, 11840,  3781,  1436, 28233, 29469, 13546,  1280,  3373,
        15709, 26829, 15174, 21022,   856, 11350,  4977, 26553, 12099, 12933,
        12624, 10371, 30338, 30338, 30338, 30338, 30338, 30338, 30338, 30338,
        30338, 30338, 30338, 30338, 30338, 30338, 30338, 30338, 30338, 3

In [28]:
import torch
a = torch.tensor([[30303, 15579, 25899, 27259, 25977, 25706,   353, 15594,  5630, 23868,
        29209, 21022, 19729,  1960, 30001, 20564, 12785, 23994,  9696, 13586,
        29469, 25054,  1475, 19127, 11985,  3170, 21310, 17047, 14281, 12099,
        12933,  8141,  4977, 12933, 27420, 20205,    0,    0,    0,    0]])           

In [29]:
from torch import nn
word_embeddings = nn.Embedding(50000, 100)
embedded = word_embeddings(a)
print(a.size())
print(embedded.size())
print(embedded)
# a.view(5,1,-1)
#a.view(len(sample), 1, -1))

torch.Size([1, 40])
torch.Size([1, 40, 100])
tensor([[[-1.3923, -1.1445,  0.1384,  ...,  0.2422,  0.4852,  0.4902],
         [-0.5394, -1.0573, -1.4659,  ..., -1.3343,  0.4385, -0.3999],
         [ 0.1653,  0.0355,  0.1190,  ..., -0.0938,  0.1412, -1.7612],
         ...,
         [-0.4802, -0.5822, -0.7314,  ..., -0.1073, -0.8257,  0.8428],
         [-0.4802, -0.5822, -0.7314,  ..., -0.1073, -0.8257,  0.8428],
         [-0.4802, -0.5822, -0.7314,  ..., -0.1073, -0.8257,  0.8428]]],
       grad_fn=<EmbeddingBackward>)


In [30]:
a[:,-1,:]

IndexError: too many indices for tensor of dimension 2

In [ ]:
tensor([[-0.9557,  0.8384,  0.9705,  ..., -0.8514,  0.0321, -0.9883],
        [-0.9557,  0.8384,  0.9705,  ..., -0.8514,  0.0321, -0.9883],
        [-0.9557,  0.8384,  0.9705,  ..., -0.8514,  0.0321, -0.9883],
        ...,
        [-0.9557,  0.8384,  0.9705,  ..., -0.8514,  0.0321, -0.9883],
        [-0.9557,  0.8384,  0.9705,  ..., -0.8514,  0.0321, -0.9883],
        [-0.9557,  0.8384,  0.9705,  ..., -0.8514,  0.0321, -0.9883]],
       grad_fn=<SelectBackward>)
tensor([[-0.0160,  0.1855,  0.0073,  ..., -0.0230,  0.0488, -0.0477],
        [ 0.0245,  0.1932,  0.0244,  ..., -0.0372,  0.1381, -0.0802],
        [ 0.0274,  0.2338,  0.0461,  ..., -0.0484,  0.1108, -0.0983],
        ...,
        [-0.0761,  0.8270, -0.0747,  ..., -0.3217,  0.2419, -0.4042],
        [-0.0813,  0.8255,  0.0396,  ..., -0.2542,  0.3420, -0.4402],
        [-0.0663,  0.8745,  0.0097,  ..., -0.3122,  0.2481, -0.3710]],

In [70]:
sample = torch.rand(2,2,3)
sample

tensor([[[0.2510, 0.1991, 0.1559],
         [0.1179, 0.1065, 0.8308]],

        [[0.2598, 0.8629, 0.1640],
         [0.8153, 0.2240, 0.6898]]])

In [ ]:
sample.size()

torch.Size([2, 2, 3])

In [76]:
sample2 = sample.permute(0,2,1)
print(sample2)
torch.argmax(sample2, dim=2)

tensor([[[0.2510, 0.1179],
         [0.1991, 0.1065],
         [0.1559, 0.8308]],

        [[0.2598, 0.8153],
         [0.8629, 0.2240],
         [0.1640, 0.6898]]])


tensor([[0, 0, 1],
        [1, 0, 1]])

In [73]:
a = torch.argmax(sample, dim=2)
print({a})

{tensor([[0, 2],
        [1, 0]])}


In [78]:
import torch
x = torch.load("saved_weights.pt")
x

OrderedDict([('embedding.weight',
              tensor([[-1.3641,  0.3324,  0.7190,  ..., -0.5538,  1.7921, -0.1599],
                      [-0.5421, -0.3172,  0.6984,  ...,  1.0932, -0.3610,  0.8771],
                      [-0.3839,  0.7729, -0.3392,  ..., -0.5566, -0.1870, -0.9657],
                      ...,
                      [-1.4310, -0.4061, -0.2849,  ..., -0.8882, -0.1645, -0.3241],
                      [-1.0102, -1.5329,  0.3289,  ...,  0.9910, -0.7470,  1.1637],
                      [-1.4748,  0.6631, -0.5386,  ..., -3.4331, -1.1510,  0.6949]])),
             ('lstm.weight_ih_l0',
              tensor([[ 0.0955, -0.0867, -0.0028,  ...,  0.0487, -0.0152, -0.0374],
                      [ 0.0479,  0.0455,  0.0779,  ...,  0.0607, -0.0685, -0.0260],
                      [-0.0570,  0.0889, -0.0931,  ..., -0.0483, -0.0595, -0.0820],
                      ...,
                      [-0.0519, -0.0474,  0.0269,  ..., -0.0555,  0.0673, -0.0313],
                      [ 0.0303,  0

In [ ]:
from modelConLL2003 import RNNBIOESTagger
from datasetConLL2003 import SlidingWindowDataset
import torch
from torch.utils.data import DataLoader

ds = SlidingWindowDataset("C:/Users/rahin/projects/paper-draft-03/data/raw/ConLL2003-bioes-valid.txt")
#ds = SlidingWindowDataset()
x1, x2, y = ds.load_dictionaries()
# read this seq2seq model: https://pytorch.org/tutorials/intermediate/seq2seq_translation_tutorial.html --> for understanding embedding dimension and output dimension  
VOCAB_SIZE = len(x1)+len(x2)+2
EMBED_DIM = 50
HIDDEN_DIM = 32
NUM_LAYERS = 2
NUM_OF_CLASSES = len(y)+1
EPOCHS = 5
LEARNING_RATE = 0.5
BATCH_SIZE = 64
# Predictions

print("Step 02. builing the model...")
model = RNNBIOESTagger(embedding_dimension= EMBED_DIM,
                            vocabulary_size=VOCAB_SIZE,
                            hidden_dimension=HIDDEN_DIM,
                            num_of_layers=NUM_LAYERS,
                            dropout=0.2,
                            output_dimension=NUM_OF_CLASSES)
print("----------------------------------------------------------------")
print("Done! here is our model:")
print(model)
print("----------------------------------------------------------------")


model.load_state_dict(torch.load("C:/Users/rahin/projects/paper-draft-03/notebooks/conLLmodel.pth"))
model.eval()

loading dictionaries...
done
Performing dataset pre-processing activities...
loading dataset: ConLL2003-bioes-valid.txt
done
Parsing the dataset now...
converting tokens to indices to tensors
done
Length matches! Hurray!
loading dictionaries...
done
Step 02. builing the model...
----------------------------------------------------------------
Done! here is our model:
RNNBIOESTagger(
  (embedding): Embedding(30340, 50)
  (lstm): LSTM(50, 32, num_layers=2, batch_first=True, dropout=0.2)
  (fc): Linear(in_features=32, out_features=35, bias=True)
  (activation_fn): Tanh()
)
----------------------------------------------------------------


RNNBIOESTagger(
  (embedding): Embedding(30340, 50)
  (lstm): LSTM(50, 32, num_layers=2, batch_first=True, dropout=0.2)
  (fc): Linear(in_features=32, out_features=35, bias=True)
  (activation_fn): Tanh()
)

In [34]:
idx_to_BIOES = {}
print("Lets make predictions")

validation_dataset = DataLoader(dataset=SlidingWindowDataset("C:/Users/rahin/projects/paper-draft-03/data/raw/ConLL2003-bioes-valid.txt"),
                                batch_size=64,
                                shuffle=True)

for key, value in y.items():
    idx_to_BIOES[value] = key

print(idx_to_BIOES)
# for idx, (sample, label) in enumerate(validation_dataset):

#     if idx > 0:
#         break
# print("Our sample to predict:")
# print(sample[0])
# print("Their actual label:")
# print(label[0])

def predict(sentence, model):

    
    # print(f"{tokens_in_line} \n {tokens_to_idx}")

    # token idx to tensor conversion
    #print(sentence)
    idx_to_torch01 = torch.tensor(sentence, dtype=torch.int64)
    idx_to_torch = idx_to_torch01.unsqueeze(1).T


    with torch.no_grad():
        output = model(idx_to_torch)
        predicted_ouput=torch.argmax(output,dim=2)
        print(predicted_ouput)
        predicted_labels = []
        for item in predicted_ouput:
            for i in item:
                predicted_labels.append(idx_to_BIOES[int(i)])
        
        return predicted_ouput, predicted_labels

model = model.to("cpu")

example = sample[0]
predicted_ouput, predictions_labels = predict(example, model)
#print(predictions)        

Lets make predictions
loading dictionaries...
done
Performing dataset pre-processing activities...
loading dataset: ConLL2003-bioes-valid.txt
done
Parsing the dataset now...
converting tokens to indices to tensors
done
Length matches! Hurray!
{0: 'E-ADVP', 1: 'E-LST', 2: 'E-PRT', 3: 'I-CONJP', 4: 'O', 5: 'E-PP', 6: 'B-CONJP', 7: 'I-LST', 8: 'B-PP', 9: 'E-INTJ', 10: '-X-', 11: 'B', 12: 'E-ADJP', 13: 'E-VP', 14: 'B-ADVP', 15: 'I', 16: 'I-PRT', 17: 'B-SBAR', 18: 'I-ADVP', 19: 'B-INTJ', 20: 'I-SBAR', 21: 'I-PP', 22: 'B-PRT', 23: 'E', 24: 'I-NP', 25: 'I-ADJP', 26: 'B-NP', 27: 'B-ADJP', 28: 'E-SBAR', 29: 'E-NP', 30: 'B-VP', 31: 'I-VP', 32: 'B-LST', 34: 'PADDING'}
tensor([[26, 24, 24, 24, 24, 24, 24, 24, 24, 24, 26, 26, 24, 24, 26, 24, 26, 34,
         34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
         34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34]])


<ipython-input-34-c158d9ee3882>:28: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  idx_to_torch01 = torch.tensor(sentence, dtype=torch.int64)


In [43]:

def binary_accuracy(preds, y):
    print(preds)
    print(y)

    correct = (preds == y)
    print(correct.sum() / len(y))
    # print(len(y))

    # # correct = (rounded_preds == y).float() 

    # _,pred_label = torch.max(rounded_preds[-1], dim=0)
    # correct = (pred_label == y).float()
    acc = correct.sum() / len(y)
    return acc

binary_accuracy(predicted_ouput, labels)

tensor([[26, 24, 24, 24, 24, 24, 24, 24, 24, 24, 26, 26, 24, 24, 26, 24, 26, 34,
         34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
         34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34]])
[tensor([[26, 24, 24,  ..., 34, 34, 34],
        [26, 24, 26,  ..., 34, 34, 34],
        [26, 30, 31,  ..., 34, 34, 34],
        ...,
        [26, 24, 24,  ..., 34, 34, 34],
        [11, 26, 24,  ..., 34, 34, 34],
        [26, 24, 26,  ..., 34, 34, 34]]), tensor([[11, 26, 15,  ..., 34, 34, 34],
        [26, 24,  4,  ..., 34, 34, 34],
        [26, 30, 26,  ..., 34, 34, 34],
        ...,
        [10, 26, 15,  ..., 34, 34, 34],
        [26, 15, 26,  ..., 34, 34, 34],
        [26, 30, 27,  ..., 34, 34, 34]]), tensor([[26, 24, 26,  ..., 34, 34, 34],
        [11, 26, 26,  ..., 34, 34, 34],
        [26, 29, 34,  ..., 34, 34, 34],
        ...,
        [26, 15, 26,  ..., 34, 34, 34],
        [26, 24,  4,  ..., 34, 34, 34],
        [26, 17, 26,  ..., 34, 34, 34]]), tenso

AttributeError: 'bool' object has no attribute 'sum'

In [41]:
samples, labels = [], []
for idx, (sample, label) in enumerate(validation_dataset):
    samples.append(sample)
    labels.append(label)

#     if idx > 0:
#         break
